// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXnp_iVNtzRSacb3eeiiGXNiqGM50gG_A',
    appId: '1:851567255670:android:6681b96135d1bccc',
    messagingSenderId: '851567255670',
    projectId: 'dschool40',
    databaseURL: 'https://dschool40.firebaseio.com',
    storageBucket: 'dschool40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvWlTz0qgBI5a-hf94jsCWGm_uI_usLo',
    appId: '1:851567255670:ios:6681b96135d1bccc',
    messagingSenderId: '851567255670',
    projectId: 'dschool40',
    databaseURL: 'https://dschool40.firebaseio.com',
    storageBucket: 'dschool40.firebasestorage.app',
    iosClientId: '851567255670-7p57qcmeeh26eorfaqcbnl0h2uhosbes.apps.googleusercontent.com',
    iosBundleId: 'com.gp.dschool40',
  );

}